[config]
model="gpt-3.5-turbo"
model_turbo="gpt-4o"

[pr_reviewer]
extra_instructions = "Please use Japanese in descriptions."

[pr_description]
extra_instructions = "Please use Japanese in descriptions."

[pr_code_suggestions]
extra_instructions = "Please use Japanese in descriptions."
